[package]
name = "masonry_android"
version = "0.1.0"
edition = "2024"

[dependencies]
accesskit = "0.19.0"
accesskit_android = "0.2.0"
android-view = { path = ".." }
masonry = { git = "https://github.com/linebender/xilem" }
pollster = "0.4.0"
tracing = "0.1.40"
vello = "0.5.0"
